#source 'https://git.coding.net/hging/Specs.git'
platform :ios,'9.3'
#use_frameworks!
target 'ReactiveCocoaDemo' do
 pod 'MJRefresh', '~> 3.1.12'
 pod 'AFNetworking', '~> 3.1.0’
 pod 'ReactiveCocoa','~>2.0'
 #pod 'MBProgressHUD', '~> 0.9.2’
 #pod 'IQKeyboardManager', '~> 3.3.5'
 #pod 'SSKeychain', '~> 1.4.0'
 #pod 'MJExtension', '~> 3.0.1'
 #pod 'IQLabelView', '~> 0.2.1'
 #pod 'SDWebImage', '~>3.8'
 #pod 'SDCycleScrollView','~> 1.65’
 #pod 'MWPhotoBrowser', '~> 2.1.2'
 #pod 'MLeaksFinder'
 #pod 'Base64', '~> 1.0.1'
 #pod 'iVersion', '~> 1.11.5'
 #pod 'FMDB', '~> 2.5'
 #pod 'DLSFTPClient', '~> 1.0.5'
 #pod 'KxMenu', '~> 1'
 #pod 'Masonry’, '~> 1.0.2’
 #pod 'GoldRaccoon', '~> 1.0.2'
 #pod 'ZLPhotoBrowser', '~> 2.0.3'
 end